### Rejestracja użytkownika
POST http://localhost:8001/auth/register
Content-Type: application/json

{
  "name": "Jan Kowalski",
  "email": "jan.kowalski@test.pl",
  "password": "Password123"
}

###

### Logowanie użytkownika
POST http://localhost:8001/auth/login
Content-Type: application/json

{
  "email":"jan.kowalski@test.pl",
  "password":"Password123"
}

###

### Test endpointu zabezpieczonego bez tokena
GET http://localhost:8001/test/secure

###

### Test endpointu zabezpieczonego z tokenem
GET http://localhost:8001/test/secure
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYW4ua293YWxza2lAdGVzdC5wbCIsImlhdCI6MTc4MDkxNTcxMiwiZXhwIjoxNzgxMDAyMTEyfQ.uHYtxNSYqCXW2wH3TOky1n48qCasm7mQxZNegsNXT6Q

### Słabe hasło
POST http://localhost:8001/auth/register
Content-Type: application/json

{
  "name":"Jan",
  "email":"abc@test.pl",
  "password":"abc"
}

###

### Niepoprawne logowanie
POST http://localhost:8001/auth/login
Content-Type: application/json

{
  "email":"jan@test.pl",
  "password":"zlehaslo"
}