
spring.datasource.url=jdbc:postgresql://130.162.56.186:5432/proj_db
spring.datasource.username=proj_admin
spring.datasource.password=Abiaxd11

#GJ: zablokowalem mozliwosc aktualizowania bazy przez Springa, trzymamy sie tego co juz jest aby uniknac nowych, zlych tabel
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect